name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=20.2.4
  - numpy=1.21.2
  - pip:
    - soundfile
    - resampy
    - scipy
    - scikit-image
    - pandas==1.3.5
    - scikit-learn==1.0.2
    - matplotlib==3.5.2
    - msrest==0.6.21
    - mlflow==1.27.0
    - torch==1.11.0
    - torchvision==0.12.0
    - opencv-python-headless==4.7.0.72
    - tensorboardX==2.6.1